---
  - name: install transport-https
    apt:
      name: apt-transport-https
      state: present
      update_cache: yes
  
  - name: install ca-certificates
    apt:
      name: ca-certificates
      state: present

  - name: install curl
    apt:
      name: curl
      state: present

  - name: install software-properties-common
    apt:
      name: software-properties-common
      state: present

  - name: add docker repo
    shell: |
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      apt-key fingerprint 0EBFCD88
      add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"

  - name: install docker-ce
    apt:
      name: docker-ce
      state: present
      update_cache: yes