---
  # - name: create user
  #   include: user.yml

  - name: install docker
    become: yes
    include: docker.yml

  - name: install basic tools
    include: basic.yml

  - name: clean cache
    include: clean.yml